# Generated by Django 5.0.6 on 2024-07-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_advertisement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='image',
            new_name='photo',
        ),
    ]
