# Generated by Django 5.0.6 on 2024-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_image_advertisement_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
