# Generated by Django 5.0.4 on 2024-06-10 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectedobject',
            options={'ordering': ['-pk'], 'verbose_name': 'Обнаруженный объект', 'verbose_name_plural': 'Обнаруженные объекты'},
        ),
        migrations.AlterModelOptions(
            name='imagefeed',
            options={'ordering': ['-pk'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='imagefeed',
            name='processed_image',
        ),
        migrations.AddField(
            model_name='detectedobject',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/', verbose_name='Обработанное изображение'),
        ),
        migrations.AlterField(
            model_name='imagefeed',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagefeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
