# Generated by Django 5.0.4 on 2024-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0002_alter_detectedobject_options_alter_imagefeed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedobject',
            name='method_detected',
            field=models.CharField(default='detr', max_length=100),
            preserve_default=False,
        ),
    ]
