# Generated by Django 5.0.6 on 2024-06-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0003_detectedobject_method_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefeed',
            name='tg_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
