# Generated by Django 5.0.6 on 2024-06-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0004_imagefeed_tg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefeed',
            name='tg_id',
        ),
    ]
