# Generated by Django 5.0.6 on 2024-06-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0006_useraddfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefeed',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefeed',
            name='lon',
            field=models.FloatField(default=0, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
