# Generated by Django 5.0.6 on 2024-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0007_imagefeed_lat_imagefeed_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefeed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
